In [1]:
import pandas as pd
import numpy as np

file_path = 'globalterrorismdb_0522dist.xlsx'

#datasource = https://www.start.umd.edu/gtd/contact/download?t=38f4a8088ba511ef95ab0e5194896103

# Read the excel file
df = pd.read_excel(file_path)

# Now the data can be worked with the DataFrame 'df' containing the data from the excel file
print(df.head())  # Print the first few rows of the DataFrame as a check

        eventid  iyear  imonth  iday approxdate  extended resolution  country  \
0  197000000001   1970       7     2        NaN         0        NaT       58
1  197000000002   1970       0     0        NaN         0        NaT      130
2  197001000001   1970       1     0        NaN         0        NaT      160
3  197001000002   1970       1     0        NaN         0        NaT       78
4  197001000003   1970       1     0        NaN         0        NaT      101

          country_txt  region  ... addnotes scite1 scite2  scite3  dbsource  \
0  Dominican Republic       2  ...      NaN    NaN    NaN     NaN      PGIS
1              Mexico       1  ...      NaN    NaN    NaN     NaN      PGIS
2         Philippines       5  ...      NaN    NaN    NaN     NaN      PGIS
3              Greece       8  ...      NaN    NaN    NaN     NaN      PGIS
4               Japan       4  ...      NaN    NaN    NaN     NaN      PGIS

   INT_LOG  INT_IDEO INT_MISC INT_ANY  related
0        0         0        0       0      NaN
1        0         1        1       1      NaN
2       -9        -9        1       1      NaN
3       -9        -9        1       1      NaN
4       -9        -9        1       1      NaN

[5 rows x 135 columns]

In [2]:
df.tail(20)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
209686,202012300016,2020,12,30,2020-12-30 00:00:00,0,NaT,92,India,6,...,NaN,"""Maoist Landmine Blast In Odisha-Chhattisgarh ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
209687,202012300017,2020,12,30,NaN,0,NaT,153,Pakistan,6,...,NaN,"""31 arrested in Pakistan after mob attacks, se...","""Mob Burns Down Hindu Temple In Pakistan's Khy...","""Hindu temple set on fire in Pakistan sees 14 ...",START Primary Collection,-9,-9,0,-9,NaN
209688,202012310001,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Civil society activist and tribal elder kille...","""Afghan War Casualty Report: December 2020,"" N...",NaN,START Primary Collection,-9,-9,0,-9,NaN
209689,202012310002,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Afghan War Casualty Report: December 2020,"" N...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209690,202012310003,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Afghanistan- A Nangarhar Reporter Realizes, I...","""Roadside bomb blast kills passer-by, injures ...","""Afghan War Casualty Report: December 2020,"" N...",START Primary Collection,0,0,0,0,NaN
209691,202012310004,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,Casualties conflict across sources. Following ...,"""Afghan War Casualty Report: December 2020,"" N...","""Afghan media highlights 31 Dec 20,"" BBC Monit...","""Terrorism Digest: 30-31 Dec 20,"" BBC Monitori...",START Primary Collection,-9,-9,0,-9,NaN
209692,202012310005,2020,12,31,NaN,0,NaT,92,India,6,...,NaN,"""Police access CCTV footage, get leads in jewe...","""Goldsmith shot dead, CRPF officer injured in ...","""Jeweller shot dead in Srinagar,"" Daily Excels...",START Primary Collection,0,0,0,0,NaN
209693,202012310006,2020,12,31,NaN,0,NaT,92,India,6,...,The victims included Hardayal Yadav.,"""Jeweller shot dead in Srinagar,"" Daily Excels...","""Goldsmith shot dead by militants in Srinagar,...","""CRPF officer injured in firing by militants i...",START Primary Collection,-9,-9,0,-9,NaN
209694,202012310007,2020,12,31,NaN,0,NaT,95,Iraq,10,...,NaN,"""Bomb reportedly targets US-led coalition conv...","""Iraq tightens security in Green Zone amid ‘an...","""Bomb blast targets US-led coalition military ...",START Primary Collection,-9,-9,1,1,NaN
209695,202012310008,2020,12,31,NaN,0,NaT,229,Democratic Republic of the Congo,11,...,NaN,"""Rights group highlights rebel abuses in DR Co...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209696,202012310009,2020,12,31,NaN,0,NaT,95,Iraq,10,...,NaN,"""Iraq experts work to defuse mine on oil tanke...","""UPDATE 1-Iraq evacuates oil tanker after mine...","""Iraq defuses mine attached to Iraqi oil tanke...",START Primary Collection,-9,-9,0,-9,NaN
209697,202012310010,2020,12,31,NaN,0,NaT,78,Greece,8,...,NaN,"""Nea: The explosion took place near the Athens...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
209698,202012310012,2020,12,31,NaN,1,NaT,229,Democratic Republic of the Congo,11,...,Casualty numbers conflict across sources. Foll...,"""At least 25 farmers ‘killed by ADF rebels’ in...","""26 civilians killed by rebels in eastern Cong...","""At least 25 killed in east DR Congo, ADF mili...",START Primary Collection,0,1,0,1,NaN
209699,202012310013,2020,12,31,NaN,0,NaT,228,Yemen,10,...,NaN,"""Yemen: Bomb targets humanitarian group in Ade...","""Blast reported at headquarters of French NGO ...",NaN,START Primary Collection,-9,-9,1,1,NaN
209700,202012310014,2020,12,31,NaN,0,NaT,141,Nepal,6,...,NaN,"""Govt vehicle torched in Jajarkot,"" Khabar Hub...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
209701,202012310015,2020,12,31,2020-12-31 00:00:00,0,NaT,228,Yemen,10,...,NaN,"""Al Houthi militia escalated in Hays and targe...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209702,202012310016,2020,12,31,2020-12-31 00:00:00,0,NaT,228,Yemen,10,...,NaN,"""Al Houthi militia escalated in Hays and targe...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209703,202012310017,2020,12,31,NaN,0,NaT,75,Germany,8,...,NaN,"""Far-left arson attack suspected on German asy...","""Fire of Bundeswehr vehicles in Leipzig, proba...","""Anarchist Antifa Take Credit for Arson Attack...",START Primary Collection,-9,-9,0,-9,NaN
209704,202012310018,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Civil society activist and tribal elder kille...","""Terrorism Digest: 1-2 Jan 21,"" BBC Monitoring...",NaN,START Primary Collection,-9,-9,0,-9,NaN
209705,202012310019,2020,12,31,NaN,1,NaT,33,Burkina Faso,11,...,NaN,"""Terrorism Digest: 3-4 Jan 21,"" BBC Monitoring...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [3]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209706 entries, 0 to 209705
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 216.0+ MB

In [4]:
df.describe()

,eventid,iyear,imonth,iday,extended,resolution,country,region,latitude,longitude,...,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,2.097060e+05,209706.000000,209706.000000,209706.000000,209706.000000,4861,209706.000000,209706.000000,205015.000000,205014.000000,...,1.533000e+03,7.340000e+02,9.510000e+02,725.000000,14091.000000,13494.000000,209706.000000,209706.000000,209706.000000,209706.000000
mean,2.004867e+11,2004.800993,6.455285,15.527930,0.051525,2006-12-14 11:22:40.581978880,130.291351,7.279854,23.358696,30.416738,...,2.791526e+06,3.211036e+05,6.204108e+05,182.750345,4.705912,-31.945531,-4.424289,-4.339318,0.086841,-3.850758
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,1970-03-08 00:00:00,4.000000,1.000000,-53.154613,-176.176447,...,-9.900000e+01,-9.900000e+01,-9.900000e+01,-99.000000,1.000000,-100.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,1.992080e+11,1992.000000,4.000000,8.000000,0.000000,1997-05-22 00:00:00,69.000000,6.000000,11.510046,8.748117,...,0.000000e+00,0.000000e+00,-9.900000e+01,0.000000,2.000000,-99.000000,-9.000000,-9.000000,0.000000,-9.000000
50%,2.012010e+11,2012.000000,6.000000,15.000000,0.000000,2013-04-29 00:00:00,98.000000,8.000000,31.300213,43.746215,...,1.000000e+04,0.000000e+00,0.000000e+00,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.015123e+11,2015.000000,9.000000,23.000000,0.000000,2016-05-10 00:00:00,160.000000,10.000000,34.557022,68.835918,...,3.420000e+05,0.000000e+00,6.640600e+02,0.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,2.020123e+11,2020.000000,12.000000,31.000000,1.000000,2021-05-29 00:00:00,1004.000000,12.000000,74.633553,179.366667,...,1.000000e+09,1.320000e+08,2.750000e+08,48000.000000,7.000000,2958.000000,1.000000,1.000000,1.000000,1.000000
std,1.351933e+09,13.519321,3.387098,8.801104,0.221066,NaN,111.714562,2.905697,18.137061,56.113029,...,2.826923e+07,5.005760e+06,9.195574e+06,2567.718184,2.030311,64.494306,4.543800,4.640302,0.536943,4.677966

In [5]:
# Set the 'max_columns' option to None to print all columns
pd.set_option('display.max_columns', None)

# Now, when you print the DataFrame,  display all columns without truncation
print(df)

             eventid  iyear  imonth  iday           approxdate  extended  \
0       197000000001   1970       7     2                  NaN         0
1       197000000002   1970       0     0                  NaN         0
2       197001000001   1970       1     0                  NaN         0
3       197001000002   1970       1     0                  NaN         0
4       197001000003   1970       1     0                  NaN         0
...              ...    ...     ...   ...                  ...       ...
209701  202012310015   2020      12    31  2020-12-31 00:00:00         0
209702  202012310016   2020      12    31  2020-12-31 00:00:00         0
209703  202012310017   2020      12    31                  NaN         0
209704  202012310018   2020      12    31                  NaN         0
209705  202012310019   2020      12    31                  NaN         1

       resolution  country         country_txt  region  \
0             NaT       58  Dominican Republic       2
1             NaT      130              Mexico       1
2             NaT      160         Philippines       5
3             NaT       78              Greece       8
4             NaT      101               Japan       4
...           ...      ...                 ...     ...
209701        NaT      228               Yemen      10
209702        NaT      228               Yemen      10
209703        NaT       75             Germany       8
209704        NaT        4         Afghanistan       6
209705        NaT       33        Burkina Faso      11

                         region_txt     provstate           city   latitude  \
0       Central America & Caribbean      National  Santo Domingo  18.456792
1                     North America       Federal    Mexico city  19.371887
2                    Southeast Asia        Tarlac        Unknown  15.478598
3                    Western Europe        Attica         Athens  37.997490
4                         East Asia       Fukouka        Fukouka  33.580412
...                             ...           ...            ...        ...
209701   Middle East & North Africa   Al Hudaydah          Sabaa  15.305307
209702   Middle East & North Africa   Al Hudaydah   Beit Maghari  13.931337
209703               Western Europe  Lower Saxony        Leipzig  51.342239
209704                   South Asia         Kabul          Kabul  34.523842
209705           Sub-Saharan Africa         Sahel          Kelbo  13.864252

         longitude  specificity  vicinity  \
0       -69.951164          1.0         0
1       -99.086624          1.0         0
2       120.599741          4.0         0
3        23.762728          1.0         0
4       130.396361          1.0         0
...            ...          ...       ...
209701   43.019490          2.0         0
209702   43.478924          2.0         0
209703   12.374772          1.0         0
209704   69.140304          1.0         0
209705   -1.161453          1.0         0

                                                 location  \
0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
209701                                                NaN
209702        The incident occurred in the Hays district.
209703                                                NaN
209704  The incident occurred in Khair Khana neighborh...
209705                                                NaN

                                                  summary  crit1  crit2  \
0                                                     NaN      1      1
1                                                     NaN      1      1
2                                                     NaN      1      1
3                                                     NaN      1      1
4                                                     NaN      1      1
...                                                   ...    ...    ...
209701  12/31/2020: Assailants fired mortar shells tar...      1      1
209702  12/31/2020: Assailants attempted to plant expl...      1      1
209703  12/31/2020: Assailants set fire to German Army...      1      1
209704  12/31/2020: Assailants shot and killed a civil...      1      1
209705  12/31/2020: Assailants attacked a Volunteers o...      1      1

        crit3  doubtterr  alternative             alternative_txt  multiple  \
0           1          0          NaN                         NaN       0.0
1           1          0          NaN                         NaN       0.0
2           1          0          NaN                         NaN       0.0
3           1          0          NaN                         NaN       0.0
4           1         -9          NaN                         NaN       0.0
...       ...        ...          ...                         ...       ...
209701      1          0          NaN                         NaN       0.0
209702      1          0          NaN                         NaN       0.0
209703      0          1          1.0  Insurgency/Guerilla Action       0.0
209704      1          0          NaN                         NaN       0.0
209705      0          1          1.0  Insurgency/Guerilla Action       0.0

        success  suicide  attacktype1                 attacktype1_txt  \
0             1        0            1                   Assassination
1             1        0            6     Hostage Taking (Kidnapping)
2             1        0            1                   Assassination
3             1        0            3               Bombing/Explosion
4             1        0            7  Facility/Infrastructure Attack
...         ...      ...          ...                             ...
209701        1        0            3               Bombing/Explosion
209702        1        0            3               Bombing/Explosion
209703        1        0            7  Facility/Infrastructure Attack
209704        1        0            2                   Armed Assault
209705        1        0            2                   Armed Assault

        attacktype2 attacktype2_txt  attacktype3 attacktype3_txt  targtype1  \
0               NaN             NaN          NaN             NaN         14
1               NaN             NaN          NaN             NaN          7
2               NaN             NaN          NaN             NaN         10
3               NaN             NaN          NaN             NaN          7
4               NaN             NaN          NaN             NaN          7
...             ...             ...          ...             ...        ...
209701          NaN             NaN          NaN             NaN         14
209702          NaN             NaN          NaN             NaN         14
209703          NaN             NaN          NaN             NaN          4
209704          NaN             NaN          NaN             NaN         14
209705          NaN             NaN          NaN             NaN          4

                      targtype1_txt  targsubtype1  \
0       Private Citizens & Property          68.0
1           Government (Diplomatic)          45.0
2               Journalists & Media          54.0
3           Government (Diplomatic)          46.0
4           Government (Diplomatic)          46.0
...                             ...           ...
209701  Private Citizens & Property          76.0
209702  Private Citizens & Property          76.0
209703                     Military          35.0
209704  Private Citizens & Property          83.0
209705                     Military          39.0

                                         targsubtype1_txt  \
0                                          Named Civilian
1       Diplomatic Personnel (outside of embassy, cons...
2                         Radio Journalist/Staff/Facility
3                                       Embassy/Consulate
4                                       Embassy/Consulate
...                                                   ...
209701                          House/Apartment/Residence
209702                          House/Apartment/Residence
209703  Military Transportation/Vehicle (excluding con...
209704                                          Protester
209705                                       Paramilitary

                                                    corp1  \
0                                                     NaN
1                             Belgian Ambassador Daughter
2                                        Voice of America
3                                                     NaN
4                                                     NaN
...                                                   ...
209701                                     Not Applicable
209702                                     Not Applicable
209703                                        German Army
209704                                     Not Applicable
209705  Volunteers of the Defence of the Fatherland (VDP)

                        target1  natlty1         natlty1_txt  targtype2  \
0                  Julio Guzman     58.0  Dominican Republic        NaN
1       Nadine Chaval, daughter     21.0             Belgium        NaN
2                      Employee    217.0       United States        NaN
3                  U.S. Embassy    217.0       United States        NaN
4                U.S. Consulate    217.0       United States        NaN
...                         ...      ...                 ...        ...
209701               Residences    228.0               Yemen        NaN
209702               Residences    228.0               Yemen        NaN
209703      Wolf-Class Vehicles     75.0             Germany        NaN
209704     Activist: Abdi Jahid      4.0         Afghanistan        NaN
209705    Paramilitary Position     33.0        Burkina Faso        NaN

       targtype2_txt  targsubtype2 targsubtype2_txt corp2 target2  natlty2  \
0                NaN           NaN              NaN   NaN     NaN      NaN
1                NaN           NaN              NaN   NaN     NaN      NaN
2                NaN           NaN              NaN   NaN     NaN      NaN
3                NaN           NaN              NaN   NaN     NaN      NaN
4                NaN           NaN              NaN   NaN     NaN      NaN
...              ...           ...              ...   ...     ...      ...
209701           NaN           NaN              NaN   NaN     NaN      NaN
209702           NaN           NaN              NaN   NaN     NaN      NaN
209703           NaN           NaN              NaN   NaN     NaN      NaN
209704           NaN           NaN              NaN   NaN     NaN      NaN
209705           NaN           NaN              NaN   NaN     NaN      NaN

       natlty2_txt  targtype3 targtype3_txt  targsubtype3 targsubtype3_txt  \
0              NaN        NaN           NaN           NaN              NaN
1              NaN        NaN           NaN           NaN              NaN
2              NaN        NaN           NaN           NaN              NaN
3              NaN        NaN           NaN           NaN              NaN
4              NaN        NaN           NaN           NaN              NaN
...            ...        ...           ...           ...              ...
209701         NaN        NaN           NaN           NaN              NaN
209702         NaN        NaN           NaN           NaN              NaN
209703         NaN        NaN           NaN           NaN              NaN
209704         NaN        NaN           NaN           NaN              NaN
209705         NaN        NaN           NaN           NaN              NaN

       corp3 target3  natlty3 natlty3_txt                               gname  \
0        NaN     NaN      NaN         NaN                              MANO-D
1        NaN     NaN      NaN         NaN  23rd of September Communist League
2        NaN     NaN      NaN         NaN                             Unknown
3        NaN     NaN      NaN         NaN                             Unknown
4        NaN     NaN      NaN         NaN                             Unknown
...      ...     ...      ...         ...                                 ...
209701   NaN     NaN      NaN         NaN     Houthi extremists (Ansar Allah)
209702   NaN     NaN      NaN         NaN     Houthi extremists (Ansar Allah)
209703   NaN     NaN      NaN         NaN                Left-wing extremists
209704   NaN     NaN      NaN         NaN                             Unknown
209705   NaN     NaN      NaN         NaN                             Unknown

       gsubname gname2 gsubname2 gname3 gsubname3 motive  guncertain1  \
0           NaN    NaN       NaN    NaN       NaN    NaN          0.0
1           NaN    NaN       NaN    NaN       NaN    NaN          0.0
2           NaN    NaN       NaN    NaN       NaN    NaN          0.0
3           NaN    NaN       NaN    NaN       NaN    NaN          0.0
4           NaN    NaN       NaN    NaN       NaN    NaN          0.0
...         ...    ...       ...    ...       ...    ...          ...
209701      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209702      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209703      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209704      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209705      NaN    NaN       NaN    NaN       NaN    NaN          0.0

        guncertain2  guncertain3  individual  nperps  nperpcap  claimed  \
0               NaN          NaN           0     NaN       NaN      NaN
1               NaN          NaN           0     7.0       NaN      NaN
2               NaN          NaN           0     NaN       NaN      NaN
3               NaN          NaN           0     NaN       NaN      NaN
4               NaN          NaN           0     NaN       NaN      NaN
...             ...          ...         ...     ...       ...      ...
209701          NaN          NaN           0   -99.0       0.0      0.0
209702          NaN          NaN           0   -99.0       0.0      0.0
209703          NaN          NaN           0   -99.0       0.0      1.0
209704          NaN          NaN           0   -99.0       0.0      0.0
209705          NaN          NaN           0   -99.0       0.0      0.0

        claimmode                  claimmode_txt  claim2  claimmode2  \
0             NaN                            NaN     NaN         NaN
1             NaN                            NaN     NaN         NaN
2             NaN                            NaN     NaN         NaN
3             NaN                            NaN     NaN         NaN
4             NaN                            NaN     NaN         NaN
...           ...                            ...     ...         ...
209701        NaN                            NaN     NaN         NaN
209702        NaN                            NaN     NaN         NaN
209703        7.0  Posted to website, blog, etc.     NaN         NaN
209704        NaN                            NaN     NaN         NaN
209705        NaN                            NaN     NaN         NaN

       claimmode2_txt  claim3  claimmode3 claimmode3_txt  compclaim  \
0                 NaN     NaN         NaN            NaN        NaN
1                 NaN     NaN         NaN            NaN        NaN
2                 NaN     NaN         NaN            NaN        NaN
3                 NaN     NaN         NaN            NaN        NaN
4                 NaN     NaN         NaN            NaN        NaN
...               ...     ...         ...            ...        ...
209701            NaN     NaN         NaN            NaN        NaN
209702            NaN     NaN         NaN            NaN        NaN
209703            NaN     NaN         NaN            NaN        NaN
209704            NaN     NaN         NaN            NaN        NaN
209705            NaN     NaN         NaN            NaN        NaN

        weaptype1 weaptype1_txt  weapsubtype1  \
0              13       Unknown           NaN
1              13       Unknown           NaN
2              13       Unknown           NaN
3               6    Explosives          16.0
4               8    Incendiary           NaN
...           ...           ...           ...
209701          6    Explosives          11.0
209702          6    Explosives           8.0
209703          8    Incendiary          18.0
209704          5      Firearms           5.0
209705          5      Firearms           5.0

                                 weapsubtype1_txt  weaptype2 weaptype2_txt  \
0                                             NaN        NaN           NaN
1                                             NaN        NaN           NaN
2                                             NaN        NaN           NaN
3                          Unknown Explosive Type        NaN           NaN
4                                             NaN        NaN           NaN
...                                           ...        ...           ...
209701  Projectile (rockets, mortars, RPGs, etc.)        NaN           NaN
209702                                   Landmine        6.0    Explosives
209703                                 Arson/Fire        NaN           NaN
209704                           Unknown Gun Type        NaN           NaN
209705                           Unknown Gun Type        NaN           NaN

        weapsubtype2        weapsubtype2_txt  weaptype3 weaptype3_txt  \
0                NaN                     NaN        NaN           NaN
1                NaN                     NaN        NaN           NaN
2                NaN                     NaN        NaN           NaN
3                NaN                     NaN        NaN           NaN
4                NaN                     NaN        NaN           NaN
...              ...                     ...        ...           ...
209701           NaN                     NaN        NaN           NaN
209702          16.0  Unknown Explosive Type        NaN           NaN
209703           NaN                     NaN        NaN           NaN
209704           NaN                     NaN        NaN           NaN
209705           NaN                     NaN        NaN           NaN

        weapsubtype3 weapsubtype3_txt  weaptype4 weaptype4_txt  weapsubtype4  \
0                NaN              NaN        NaN           NaN           NaN
1                NaN              NaN        NaN           NaN           NaN
2                NaN              NaN        NaN           NaN           NaN
3                NaN              NaN        NaN           NaN           NaN
4                NaN              NaN        NaN           NaN           NaN
...              ...              ...        ...           ...           ...
209701           NaN              NaN        NaN           NaN           NaN
209702           NaN              NaN        NaN           NaN           NaN
209703           NaN              NaN        NaN           NaN           NaN
209704           NaN              NaN        NaN           NaN           NaN
209705           NaN              NaN        NaN           NaN           NaN

       weapsubtype4_txt                        weapdetail  nkill  nkillus  \
0                   NaN                               NaN    1.0      NaN
1                   NaN                               NaN    0.0      NaN
2                   NaN                               NaN    1.0      NaN
3                   NaN                         Explosive    NaN      NaN
4                   NaN                        Incendiary    NaN      NaN
...                 ...                               ...    ...      ...

In [6]:
# Step 1: Get insights about the dataset
print("Dataset Info:")
print(df.info())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209706 entries, 0 to 209705
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 216.0+ MB
None

In [7]:
print("\nSummary Statistics:")
print(df.describe())

Summary Statistics:
            eventid          iyear         imonth           iday  \
count  2.097060e+05  209706.000000  209706.000000  209706.000000
mean   2.004867e+11    2004.800993       6.455285      15.527930
min    1.970000e+11    1970.000000       0.000000       0.000000
25%    1.992080e+11    1992.000000       4.000000       8.000000
50%    2.012010e+11    2012.000000       6.000000      15.000000
75%    2.015123e+11    2015.000000       9.000000      23.000000
max    2.020123e+11    2020.000000      12.000000      31.000000
std    1.351933e+09      13.519321       3.387098       8.801104

            extended                     resolution        country  \
count  209706.000000                           4861  209706.000000
mean        0.051525  2006-12-14 11:22:40.581978880     130.291351
min         0.000000            1970-03-08 00:00:00       4.000000
25%         0.000000            1997-05-22 00:00:00      69.000000
50%         0.000000            2013-04-29 00:00:00      98.000000
75%         0.000000            2016-05-10 00:00:00     160.000000
max         1.000000            2021-05-29 00:00:00    1004.000000
std         0.221066                            NaN     111.714562

              region       latitude      longitude    specificity  \
count  209706.000000  205015.000000  205014.000000  209705.000000
mean        7.279854      23.358696      30.416738       1.468387
min         1.000000     -53.154613    -176.176447       1.000000
25%         6.000000      11.510046       8.748117       1.000000
50%         8.000000      31.300213      43.746215       1.000000
75%        10.000000      34.557022      68.835918       1.000000
max        12.000000      74.633553     179.366667       5.000000
std         2.905697      18.137061      56.113029       0.984958

            vicinity          crit1          crit2          crit3  \
count  209706.000000  209706.000000  209706.000000  209706.000000
mean        0.068854       0.988265       0.993291       0.866246
min        -9.000000       0.000000       0.000000       0.000000
25%         0.000000       1.000000       1.000000       1.000000
50%         0.000000       1.000000       1.000000       1.000000
75%         0.000000       1.000000       1.000000       1.000000
max         1.000000       1.000000       1.000000       1.000000
std         0.281308       0.107693       0.081636       0.340389

           doubtterr   alternative       multiple        success  \
count  209706.000000  35249.000000  209705.000000  209706.000000
mean       -0.423593      1.293001       0.145900       0.883628
min        -9.000000      1.000000       0.000000       0.000000
25%         0.000000      1.000000       0.000000       1.000000
50%         0.000000      1.000000       0.000000       1.000000
75%         0.000000      1.000000       0.000000       1.000000
max         1.000000      5.000000       1.000000       1.000000
std         2.305025      0.733146       0.353007       0.320672

             suicide    attacktype1  attacktype2  attacktype3      targtype1  \
count  209706.000000  209706.000000  8434.000000   658.000000  209706.000000
mean        0.035469       3.351311     3.956011     5.705167       8.484078
min         0.000000       1.000000     1.000000     1.000000       1.000000
25%         0.000000       2.000000     2.000000     5.250000       3.000000
50%         0.000000       3.000000     2.000000     7.000000       4.000000
75%         0.000000       3.000000     7.000000     7.000000      14.000000
max         1.000000       9.000000     9.000000     7.000000      22.000000
std         0.184962       2.029153     2.358046     2.089622       6.602032

        targsubtype1        natlty1     targtype2  targsubtype2       natlty2  \
count  197867.000000  207692.000000  14535.000000  14003.000000  14211.000000
mean       47.163034     127.079035     10.050705     54.641720    126.196749
min         1.000000       4.000000      1.000000      1.000000      4.000000
25%        22.000000      78.000000      4.000000     29.000000     60.000000
50%        35.000000     101.000000     14.000000     67.000000     97.000000
75%        74.000000     175.000000     14.000000     68.000000    182.000000
max       113.000000    1004.000000     22.000000    113.000000   1004.000000
std        30.599430      91.732261      5.732859     25.761594    122.995161

         targtype3  targsubtype3      natlty3    guncertain1  guncertain2  \
count  1629.000000   1539.000000  1600.000000  209326.000000  2538.000000
mean     10.171885     55.948668   132.108125       0.075949     0.258077
min       1.000000      1.000000     4.000000       0.000000     0.000000
25%       4.000000     32.000000    45.000000       0.000000     0.000000
50%      14.000000     67.000000    98.500000       0.000000     0.000000
75%      14.000000     73.000000   182.000000       0.000000     1.000000
max      22.000000    113.000000  1004.000000       1.000000     1.000000
std       5.649132     25.870299   152.871895       0.264916     0.437663

       guncertain3     individual         nperps       nperpcap  \
count   410.000000  209706.000000  138613.000000  140233.000000
mean      0.185366       0.003929     -68.819613      -1.341261
min       0.000000       0.000000     -99.000000     -99.000000
25%       0.000000       0.000000     -99.000000       0.000000
50%       0.000000       0.000000     -99.000000       0.000000
75%       0.000000       0.000000     -99.000000       0.000000
max       1.000000       1.000000   25000.000000     406.000000
std       0.389069       0.062561     194.556994      12.115647

             claimed     claimmode       claim2  claimmode2      claim3  \
count  143613.000000  24696.000000  2476.000000  732.000000  409.000000
mean        0.079095      7.069768     0.235864    7.312842    0.337408
min        -9.000000      0.000000    -9.000000    1.000000    0.000000
25%         0.000000      7.000000     0.000000    6.000000    0.000000
50%         0.000000      8.000000     0.000000    8.000000    0.000000
75%         0.000000      8.000000     1.000000   10.000000    1.000000
max         1.000000     10.000000     1.000000   10.000000    1.000000
std         0.997974      2.343068     0.872997    2.683832    0.473405

       claimmode3    compclaim      weaptype1   weapsubtype1     weaptype2  \
count  140.000000  4954.000000  209706.000000  183765.000000  16402.000000
mean     6.692857    -6.131005       6.543060      11.081294      6.986404
min      1.000000    -9.000000       1.000000       1.000000      1.000000
25%      4.000000    -9.000000       5.000000       5.000000      5.000000
50%      7.000000    -9.000000       6.000000      11.000000      6.000000
75%      9.000000     0.000000       6.000000      16.000000      8.000000
max     10.000000     1.000000      13.000000      31.000000     13.000000
std      2.853488     4.318717       2.296739       6.485577      2.377310

       weapsubtype2    weaptype3  weapsubtype3  weaptype4  weapsubtype4  \
count  14292.000000  2371.000000   2132.000000  73.000000     70.000000
mean      11.206969     7.138338     12.407598   6.246575     10.842857
min        1.000000     2.000000      1.000000   5.000000      2.000000
25%        5.000000     5.000000      4.000000   5.000000      3.000000
50%        8.000000     7.000000     11.000000   6.000000      9.500000
75%       18.000000     9.000000     21.000000   6.000000     16.000000
max       31.000000    13.000000     28.000000  12.000000     28.000000
std        7.727262     2.239521      8.731212   1.507212      8.192672

               nkill        nkillus       nkillter         nwound  \
count  197179.000000  145269.000000  141547.000000  189770.000000
mean        2.431030       0.038797       0.559122       3.085872
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         2.000000       0.000000       0.000000       2.000000
max      1700.000000    1361.000000     500.000000   10878.000000
std        11.340882       5.109512       4.262644      40.916175

            nwoundus       nwoundte       property    propextent  \
count  145009.000000  138800.000000  209706.000000  73464.000000
mean        0.034177       0.137759      -0.712927      3.289407
min         0.000000       0.000000      -9.000000      1.000000
25%         0.000000       0.000000       0.000000      3.000000
50%         0.000000       0.000000       0.000000      3.000000
75%         0.000000       0.000000       1.000000      4.000000
max       751.000000     200.000000       1.000000      7.000000
std         2.760472       1.560821       3.288812      0.481360

          propvalue      ishostkid      nhostkid    nhostkidus       nhours  \
count  4.837500e+04  209528.000000  16667.000000  16612.000000  4985.000000
mean   1.750017e+05       0.052967      3.040559     -0.311281   -55.121916
min   -9.900000e+01      -9.000000    -99.000000    -99.000000   -99.000000
25%   -9.900000e+01       0.000000      1.000000      0.000000   -99.000000
50%   -9.900000e+01       0.000000      2.000000      0.000000   -99.000000
75%   -9.900000e+01       0.000000      4.000000      0.000000     0.000000
max    2.700000e+09       1.000000  17000.000000     86.000000   999.000000
std    1.398607e+07       0.562180    183.207589      6.355005    77.612689

              ndays        ransom     ransomamt   ransomamtus    ransompaid  \
count  10301.000000  80466.000000  1.533000e+03  7.340000e+02  9.510000e+02
mean     -36.012717     -0.157520  2.791526e+06  3.211036e+05  6.204108e+05
min      -99.000000     -9.000000 -9.900000e+01 -9.900000e+01 -9.900000e+01
25%      -99.000000      0.000000  0.000000e+00  0.000000e+00 -9.900000e+01
50%      -99.000000      0.000000  1.000000e+04  0.000000e+00  0.000000e+00
75%        3.000000      0.000000  3.420000e+05  0.000000e+00  6.640600e+02
max     2676.000000      1.000000  1.000000e+09  1.320000e+08  2.750000e+08
std      127.146650      1.255812  2.826923e+07  5.005760e+06  9.195574e+06

       ransompaidus  hostkidoutcome     nreleased        INT_LOG  \
count    725.000000    14091.000000  13494.000000  209706.000000
mean     182.750345        4.705912    -31.945531      -4.424289
min      -99.000000        1.000000   -100.000000      -9.000000
25%        0.000000        2.000000    -99.000000      -9.000000
50%        0.000000        4.000000      0.000000       0.000000
75%        0.000000        7.000000      1.000000       0.000000
max    48000.000000        7.000000   2958.000000       1.000000
std     2567.718184        2.030311     64.494306       4.543800

            INT_IDEO       INT_MISC        INT_ANY
count  209706.000000  209706.000000  209706.000000
mean       -4.339318       0.086841      -3.850758
min        -9.000000      -9.000000      -9.000000
25%        -9.000000       0.000000      -9.000000
50%         0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000
std         4.640302       0.536943       4.677966

In [8]:
# Step 2: Deal with null values
null_percentages = df.isnull().mean() * 100

In [9]:
print("\nPercentage of null values in each column:")
print(null_percentages)

Percentage of null values in each column:
eventid        0.000000
iyear          0.000000
imonth         0.000000
iday           0.000000
approxdate    93.949148
                ...
INT_LOG        0.000000
INT_IDEO       0.000000
INT_MISC       0.000000
INT_ANY        0.000000
related       85.406235
Length: 135, dtype: float64

In [10]:


# Create a dataframe with the sorted percentages
null_df = pd.DataFrame({'Column': null_percentages.index, 'Null Percentage': null_percentages.values})

# Display all rows of the dataframe
pd.set_option('display.max_rows', None)
print(null_df)

                 Column  Null Percentage
0               eventid         0.000000
1                 iyear         0.000000
2                imonth         0.000000
3                  iday         0.000000
4            approxdate        93.949148
5              extended         0.000000
6            resolution        97.681993
7               country         0.000000
8           country_txt         0.000000
9                region         0.000000
10           region_txt         0.000000
11            provstate         0.000000
12                 city         0.203618
13             latitude         2.236941
14            longitude         2.237418
15          specificity         0.000477
16             vicinity         0.000000
17             location        67.824001
18              summary        31.529856
19                crit1         0.000000
20                crit2         0.000000
21                crit3         0.000000
22            doubtterr         0.000000
23          alternative        83.191230
24      alternative_txt        83.191230
25             multiple         0.000477
26              success         0.000000
27              suicide         0.000000
28          attacktype1         0.000000
29      attacktype1_txt         0.000000
30          attacktype2        95.978179
31      attacktype2_txt        95.978179
32          attacktype3        99.686227
33      attacktype3_txt        99.686227
34            targtype1         0.000000
35        targtype1_txt         0.000000
36         targsubtype1         5.645523
37     targsubtype1_txt         5.645523
38                corp1        20.283635
39              target1         0.303759
40              natlty1         0.960392
41          natlty1_txt         0.960392
42            targtype2        93.068868
43        targtype2_txt        93.068868
44         targsubtype2        93.322556
45     targsubtype2_txt        93.322556
46                corp2        93.558601
47              target2        93.128475
48              natlty2        93.223370
49          natlty2_txt        93.223370
50            targtype3        99.223198
51        targtype3_txt        99.223198
52         targsubtype3        99.266115
53     targsubtype3_txt        99.266115
54                corp3        99.295204
55              target3        99.223675
56              natlty3        99.237027
57          natlty3_txt        99.237027
58                gname         0.000000
59             gsubname        96.552316
60               gname2        98.770183
61            gsubname2        99.912258
62               gname3        99.802581
63            gsubname3        99.989032
64               motive        73.745148
65          guncertain1         0.181206
66          guncertain2        98.789734
67          guncertain3        99.804488
68           individual         0.000000
69               nperps        33.901271
70             nperpcap        33.128761
71              claimed        31.516981
72            claimmode        88.223513
73        claimmode_txt        88.223513
74               claim2        98.819299
75           claimmode2        99.650940
76       claimmode2_txt        99.650940
77               claim3        99.804965
78           claimmode3        99.933240
79       claimmode3_txt        99.933240
80            compclaim        97.637645
81            weaptype1         0.000000
82        weaptype1_txt         0.000000
83         weapsubtype1        12.370175
84     weapsubtype1_txt        12.370175
85            weaptype2        92.178574
86        weaptype2_txt        92.178574
87         weapsubtype2        93.184744
88     weapsubtype2_txt        93.184744
89            weaptype3        98.869369
90        weaptype3_txt        98.869369
91         weapsubtype3        98.983339
92     weapsubtype3_txt        98.983339
93            weaptype4        99.965189
94        weaptype4_txt        99.965189
95         weapsubtype4        99.966620
96     weapsubtype4_txt        99.966620
97           weapdetail        41.281127
98                nkill         5.973601
99              nkillus        30.727304
100            nkillter        32.502170
101              nwound         9.506643
102            nwoundus        30.851287
103            nwoundte        33.812099
104            property         0.000000
105          propextent        64.968098
106      propextent_txt        64.968098
107           propvalue        76.931991
108         propcomment        67.848321
109           ishostkid         0.084881
110            nhostkid        92.052206
111          nhostkidus        92.078434
112              nhours        97.622862
113               ndays        95.087885
114              divert        99.838822
115       kidhijcountry        98.420169
116              ransom        61.629138
117           ransomamt        99.268977
118         ransomamtus        99.649986
119          ransompaid        99.546508
120        ransompaidus        99.654278
121          ransomnote        99.726760
122      hostkidoutcome        93.280593
123  hostkidoutcome_txt        93.280593
124           nreleased        93.565277
125            addnotes        82.924189
126              scite1        31.559421
127              scite2        55.774751
128              scite3        74.881024
129            dbsource         0.000000
130             INT_LOG         0.000000
131            INT_IDEO         0.000000
132            INT_MISC         0.000000
133             INT_ANY         0.000000
134             related        85.406235

In [11]:
# 1. Remove columns with extremely high null percentages (>95%) or redundant information
cols_to_drop = [
    'resolution', 'approxdate', 'alternative', 'alternative_txt',
    'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt',
    'targtype2', 'targtype2_txt', 'targsubtype2', 'targsubtype2_txt', 'corp2', 'target2', 'natlty2', 'natlty2_txt',
    'targtype3', 'targtype3_txt', 'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3', 'natlty3', 'natlty3_txt',
    'gsubname', 'gname2', 'gsubname2', 'gname3', 'gsubname3', 'guncertain2', 'guncertain3',
    'claim2', 'claimmode2', 'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt', 'compclaim',
    'weaptype2', 'weaptype2_txt', 'weapsubtype2', 'weapsubtype2_txt',
    'weaptype3', 'weaptype3_txt', 'weapsubtype3', 'weapsubtype3_txt',
    'weaptype4', 'weaptype4_txt', 'weapsubtype4', 'weapsubtype4_txt',
    'nhostkidus', 'nhours', 'ndays', 'kidhijcountry', 'ransom', 'ransomamt', 'ransomamtus', 'ransompaid', 'ransompaidus', 'ransomnote',
    'scite2', 'scite3', 'related'
]

In [12]:
# Calculate null percentages for the specified columns
null_percentages = df[cols_to_drop].isnull().mean() * 100

In [13]:
df = df.drop(columns=cols_to_drop)
print(f"Shape after dropping high-null columns: {df.shape}")

Shape after dropping high-null columns: (209706, 72)

In [14]:
# Create a DataFrame with the results
results_df = pd.DataFrame({
    'Column': null_percentages.index,
    'Null Percentage': null_percentages.values
})

In [15]:
results_df

              Column  Null Percentage
0         resolution        97.681993
1         approxdate        93.949148
2        alternative        83.191230
3    alternative_txt        83.191230
4        attacktype2        95.978179
5    attacktype2_txt        95.978179
6        attacktype3        99.686227
7    attacktype3_txt        99.686227
8          targtype2        93.068868
9      targtype2_txt        93.068868
10      targsubtype2        93.322556
11  targsubtype2_txt        93.322556
12             corp2        93.558601
13           target2        93.128475
14           natlty2        93.223370
15       natlty2_txt        93.223370
16         targtype3        99.223198
17     targtype3_txt        99.223198
18      targsubtype3        99.266115
19  targsubtype3_txt        99.266115
20             corp3        99.295204
21           target3        99.223675
22           natlty3        99.237027
23       natlty3_txt        99.237027
24          gsubname        96.552316
25            gname2        98.770183
26         gsubname2        99.912258
27            gname3        99.802581
28         gsubname3        99.989032
29       guncertain2        98.789734
30       guncertain3        99.804488
31            claim2        98.819299
32        claimmode2        99.650940
33    claimmode2_txt        99.650940
34            claim3        99.804965
35        claimmode3        99.933240
36    claimmode3_txt        99.933240
37         compclaim        97.637645
38         weaptype2        92.178574
39     weaptype2_txt        92.178574
40      weapsubtype2        93.184744
41  weapsubtype2_txt        93.184744
42         weaptype3        98.869369
43     weaptype3_txt        98.869369
44      weapsubtype3        98.983339
45  weapsubtype3_txt        98.983339
46         weaptype4        99.965189
47     weaptype4_txt        99.965189
48      weapsubtype4        99.966620
49  weapsubtype4_txt        99.966620
50        nhostkidus        92.078434
51            nhours        97.622862
52             ndays        95.087885
53     kidhijcountry        98.420169
54            ransom        61.629138
55         ransomamt        99.268977
56       ransomamtus        99.649986
57        ransompaid        99.546508
58      ransompaidus        99.654278
59        ransomnote        99.726760
60            scite2        55.774751
61            scite3        74.881024
62           related        85.406235

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209706 entries, 0 to 209705
Data columns (total 72 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   eventid             209706 non-null  int64
 1   iyear               209706 non-null  int64
 2   imonth              209706 non-null  int64
 3   iday                209706 non-null  int64
 4   extended            209706 non-null  int64
 5   country             209706 non-null  int64
 6   country_txt         209706 non-null  object
 7   region              209706 non-null  int64
 8   region_txt          209706 non-null  object
 9   provstate           209706 non-null  object
 10  city                209279 non-null  object
 11  latitude            205015 non-null  float64
 12  longitude           205014 non-null  float64
 13  specificity         209705 non-null  float64
 14  vicinity            209706 non-null  int64
 15  location            67475 non-null   object
 16  summary             143586 non-null  object
 17  crit1               209706 non-null  int64
 18  crit2               209706 non-null  int64
 19  crit3               209706 non-null  int64
 20  doubtterr           209706 non-null  int64
 21  multiple            209705 non-null  float64
 22  success             209706 non-null  int64
 23  suicide             209706 non-null  int64
 24  attacktype1         209706 non-null  int64
 25  attacktype1_txt     209706 non-null  object
 26  targtype1           209706 non-null  int64
 27  targtype1_txt       209706 non-null  object
 28  targsubtype1        197867 non-null  float64
 29  targsubtype1_txt    197867 non-null  object
 30  corp1               167170 non-null  object
 31  target1             209069 non-null  object
 32  natlty1             207692 non-null  float64
 33  natlty1_txt         207692 non-null  object
 34  gname               209706 non-null  object
 35  motive              55058 non-null   object
 36  guncertain1         209326 non-null  float64
 37  individual          209706 non-null  int64
 38  nperps              138613 non-null  float64
 39  nperpcap            140233 non-null  float64
 40  claimed             143613 non-null  float64
 41  claimmode           24696 non-null   float64
 42  claimmode_txt       24696 non-null   object
 43  weaptype1           209706 non-null  int64
 44  weaptype1_txt       209706 non-null  object
 45  weapsubtype1        183765 non-null  float64
 46  weapsubtype1_txt    183765 non-null  object
 47  weapdetail          123137 non-null  object
 48  nkill               197179 non-null  float64
 49  nkillus             145269 non-null  float64
 50  nkillter            141547 non-null  float64
 51  nwound              189770 non-null  float64
 52  nwoundus            145009 non-null  float64
 53  nwoundte            138800 non-null  float64
 54  property            209706 non-null  int64
 55  propextent          73464 non-null   float64
 56  propextent_txt      73464 non-null   object
 57  propvalue           48375 non-null   float64
 58  propcomment         67424 non-null   object
 59  ishostkid           209528 non-null  float64
 60  nhostkid            16667 non-null   float64
 61  divert              338 non-null     object
 62  hostkidoutcome      14091 non-null   float64
 63  hostkidoutcome_txt  14091 non-null   object
 64  nreleased           13494 non-null   float64
 65  addnotes            35809 non-null   object
 66  scite1              143524 non-null  object
 67  dbsource            209706 non-null  object
 68  INT_LOG             209706 non-null  int64
 69  INT_IDEO            209706 non-null  int64
 70  INT_MISC            209706 non-null  int64
 71  INT_ANY             209706 non-null  int64
dtypes: float64(24), int64(23), object(25)
memory usage: 115.2+ MB

In [19]:
df.isnull().sum()

eventid                    0
iyear                      0
imonth                     0
iday                       0
extended                   0
country                    0
country_txt                0
region                     0
region_txt                 0
provstate                  0
city                     427
latitude                4691
longitude               4692
specificity                1
vicinity                   0
location              142231
summary                66120
crit1                      0
crit2                      0
crit3                      0
doubtterr                  0
multiple                   1
success                    0
suicide                    0
attacktype1                0
attacktype1_txt            0
targtype1                  0
targtype1_txt              0
targsubtype1           11839
targsubtype1_txt       11839
corp1                  42536
target1                  637
natlty1                 2014
natlty1_txt             2014
gname                      0
motive                154648
guncertain1              380
individual                 0
nperps                 71093
nperpcap               69473
claimed                66093
claimmode             185010
claimmode_txt         185010
weaptype1                  0
weaptype1_txt              0
weapsubtype1           25941
weapsubtype1_txt       25941
weapdetail             86569
nkill                  12527
nkillus                64437
nkillter               68159
nwound                 19936
nwoundus               64697
nwoundte               70906
property                   0
propextent            136242
propextent_txt        136242
propvalue             161331
propcomment           142282
ishostkid                178
nhostkid              193039
divert                209368
hostkidoutcome        195615
hostkidoutcome_txt    195615
nreleased             196212
addnotes              173897
scite1                 66182
dbsource                   0
INT_LOG                    0
INT_IDEO                   0
INT_MISC                   0
INT_ANY                    0
dtype: int64