In [ ]:
import pandas as pd
import numpy as np

file_path = '/content/drive/MyDrive/globalterrorismdb_0522dist.xlsx'

#datasource = https://www.start.umd.edu/gtd/contact/download?t=38f4a8088ba511ef95ab0e5194896103

# Read the excel file
df = pd.read_excel('/content/drive/MyDrive/globalterrorismdb_0522dist.xlsx')

# Now the data can be worked with the DataFrame 'df' containing the data from the excel file
print(df.head())  # Print the first few rows of the DataFrame as a check

        eventid  iyear  imonth  iday approxdate  extended resolution  country  \
0  197000000001   1970       7     2        NaN         0        NaT       58
1  197000000002   1970       0     0        NaN         0        NaT      130
2  197001000001   1970       1     0        NaN         0        NaT      160
3  197001000002   1970       1     0        NaN         0        NaT       78
4  197001000003   1970       1     0        NaN         0        NaT      101

          country_txt  region  ... addnotes scite1 scite2  scite3  dbsource  \
0  Dominican Republic       2  ...      NaN    NaN    NaN     NaN      PGIS
1              Mexico       1  ...      NaN    NaN    NaN     NaN      PGIS
2         Philippines       5  ...      NaN    NaN    NaN     NaN      PGIS
3              Greece       8  ...      NaN    NaN    NaN     NaN      PGIS
4               Japan       4  ...      NaN    NaN    NaN     NaN      PGIS

   INT_LOG  INT_IDEO INT_MISC INT_ANY  related
0        0         0        0       0      NaN
1        0         1        1       1      NaN
2       -9        -9        1       1      NaN
3       -9        -9        1       1      NaN
4       -9        -9        1       1      NaN

[5 rows x 135 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.tail(20)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
209686,202012300016,2020,12,30,2020-12-30 00:00:00,0,NaT,92,India,6,...,NaN,"""Maoist Landmine Blast In Odisha-Chhattisgarh ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
209687,202012300017,2020,12,30,NaN,0,NaT,153,Pakistan,6,...,NaN,"""31 arrested in Pakistan after mob attacks, se...","""Mob Burns Down Hindu Temple In Pakistan's Khy...","""Hindu temple set on fire in Pakistan sees 14 ...",START Primary Collection,-9,-9,0,-9,NaN
209688,202012310001,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Civil society activist and tribal elder kille...","""Afghan War Casualty Report: December 2020,"" N...",NaN,START Primary Collection,-9,-9,0,-9,NaN
209689,202012310002,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Afghan War Casualty Report: December 2020,"" N...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209690,202012310003,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Afghanistan- A Nangarhar Reporter Realizes, I...","""Roadside bomb blast kills passer-by, injures ...","""Afghan War Casualty Report: December 2020,"" N...",START Primary Collection,0,0,0,0,NaN
209691,202012310004,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,Casualties conflict across sources. Following ...,"""Afghan War Casualty Report: December 2020,"" N...","""Afghan media highlights 31 Dec 20,"" BBC Monit...","""Terrorism Digest: 30-31 Dec 20,"" BBC Monitori...",START Primary Collection,-9,-9,0,-9,NaN
209692,202012310005,2020,12,31,NaN,0,NaT,92,India,6,...,NaN,"""Police access CCTV footage, get leads in jewe...","""Goldsmith shot dead, CRPF officer injured in ...","""Jeweller shot dead in Srinagar,"" Daily Excels...",START Primary Collection,0,0,0,0,NaN
209693,202012310006,2020,12,31,NaN,0,NaT,92,India,6,...,The victims included Hardayal Yadav.,"""Jeweller shot dead in Srinagar,"" Daily Excels...","""Goldsmith shot dead by militants in Srinagar,...","""CRPF officer injured in firing by militants i...",START Primary Collection,-9,-9,0,-9,NaN
209694,202012310007,2020,12,31,NaN,0,NaT,95,Iraq,10,...,NaN,"""Bomb reportedly targets US-led coalition conv...","""Iraq tightens security in Green Zone amid ‘an...","""Bomb blast targets US-led coalition military ...",START Primary Collection,-9,-9,1,1,NaN
209695,202012310008,2020,12,31,NaN,0,NaT,229,Democratic Republic of the Congo,11,...,NaN,"""Rights group highlights rebel abuses in DR Co...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209696,202012310009,2020,12,31,NaN,0,NaT,95,Iraq,10,...,NaN,"""Iraq experts work to defuse mine on oil tanke...","""UPDATE 1-Iraq evacuates oil tanker after mine...","""Iraq defuses mine attached to Iraqi oil tanke...",START Primary Collection,-9,-9,0,-9,NaN
209697,202012310010,2020,12,31,NaN,0,NaT,78,Greece,8,...,NaN,"""Nea: The explosion took place near the Athens...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
209698,202012310012,2020,12,31,NaN,1,NaT,229,Democratic Republic of the Congo,11,...,Casualty numbers conflict across sources. Foll...,"""At least 25 farmers ‘killed by ADF rebels’ in...","""26 civilians killed by rebels in eastern Cong...","""At least 25 killed in east DR Congo, ADF mili...",START Primary Collection,0,1,0,1,NaN
209699,202012310013,2020,12,31,NaN,0,NaT,228,Yemen,10,...,NaN,"""Yemen: Bomb targets humanitarian group in Ade...","""Blast reported at headquarters of French NGO ...",NaN,START Primary Collection,-9,-9,1,1,NaN
209700,202012310014,2020,12,31,NaN,0,NaT,141,Nepal,6,...,NaN,"""Govt vehicle torched in Jajarkot,"" Khabar Hub...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
209701,202012310015,2020,12,31,2020-12-31 00:00:00,0,NaT,228,Yemen,10,...,NaN,"""Al Houthi militia escalated in Hays and targe...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209702,202012310016,2020,12,31,2020-12-31 00:00:00,0,NaT,228,Yemen,10,...,NaN,"""Al Houthi militia escalated in Hays and targe...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209703,202012310017,2020,12,31,NaN,0,NaT,75,Germany,8,...,NaN,"""Far-left arson attack suspected on German asy...","""Fire of Bundeswehr vehicles in Leipzig, proba...","""Anarchist Antifa Take Credit for Arson Attack...",START Primary Collection,-9,-9,0,-9,NaN
209704,202012310018,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Civil society activist and tribal elder kille...","""Terrorism Digest: 1-2 Jan 21,"" BBC Monitoring...",NaN,START Primary Collection,-9,-9,0,-9,NaN
209705,202012310019,2020,12,31,NaN,1,NaT,33,Burkina Faso,11,...,NaN,"""Terrorism Digest: 3-4 Jan 21,"" BBC Monitoring...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [ ]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209706 entries, 0 to 209705
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 216.0+ MB

In [ ]:
df.describe()

,eventid,iyear,imonth,iday,extended,resolution,country,region,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,alternative,multiple,success,suicide,attacktype1,attacktype2,attacktype3,targtype1,targsubtype1,natlty1,targtype2,targsubtype2,natlty2,targtype3,targsubtype3,natlty3,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claim2,claimmode2,claim3,claimmode3,compclaim,weaptype1,weapsubtype1,weaptype2,weapsubtype2,weaptype3,weapsubtype3,weaptype4,weapsubtype4,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,ishostkid,nhostkid,nhostkidus,nhours,ndays,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,2.097060e+05,209706.000000,209706.000000,209706.000000,209706.000000,4861,209706.000000,209706.000000,205015.000000,205014.000000,209705.000000,209706.000000,209706.000000,209706.000000,209706.000000,209706.000000,35249.000000,209705.000000,209706.000000,209706.000000,209706.000000,8434.000000,658.000000,209706.000000,197867.000000,207692.000000,14535.000000,14003.000000,14211.000000,1629.000000,1539.000000,1600.000000,209326.000000,2538.000000,410.000000,209706.000000,138613.000000,140233.000000,143613.000000,24696.000000,2476.000000,732.000000,409.000000,140.000000,4954.000000,209706.000000,183765.000000,16402.000000,14292.000000,2371.000000,2132.000000,73.000000,70.000000,197179.000000,145269.000000,141547.000000,189770.000000,145009.000000,138800.000000,209706.000000,73464.000000,4.837500e+04,209528.000000,16667.000000,16612.000000,4985.000000,10301.000000,80466.000000,1.533000e+03,7.340000e+02,9.510000e+02,725.000000,14091.000000,13494.000000,209706.000000,209706.000000,209706.000000,209706.000000
mean,2.004867e+11,2004.800993,6.455285,15.527930,0.051525,2006-12-14 11:22:40.581978880,130.291351,7.279854,23.358696,30.416738,1.468387,0.068854,0.988265,0.993291,0.866246,-0.423593,1.293001,0.145900,0.883628,0.035469,3.351311,3.956011,5.705167,8.484078,47.163034,127.079035,10.050705,54.641720,126.196749,10.171885,55.948668,132.108125,0.075949,0.258077,0.185366,0.003929,-68.819613,-1.341261,0.079095,7.069768,0.235864,7.312842,0.337408,6.692857,-6.131005,6.543060,11.081294,6.986404,11.206969,7.138338,12.407598,6.246575,10.842857,2.431030,0.038797,0.559122,3.085872,0.034177,0.137759,-0.712927,3.289407,1.750017e+05,0.052967,3.040559,-0.311281,-55.121916,-36.012717,-0.157520,2.791526e+06,3.211036e+05,6.204108e+05,182.750345,4.705912,-31.945531,-4.424289,-4.339318,0.086841,-3.850758
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,1970-03-08 00:00:00,4.000000,1.000000,-53.154613,-176.176447,1.000000,-9.000000,0.000000,0.000000,0.000000,-9.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,-9.000000,0.000000,-9.000000,1.000000,0.000000,1.000000,-9.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,1.000000,-9.900000e+01,-9.000000,-99.000000,-99.000000,-99.000000,-99.000000,-9.000000,-9.900000e+01,-9.900000e+01,-9.900000e+01,-99.000000,1.000000,-100.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,1.992080e+11,1992.000000,4.000000,8.000000,0.000000,1997-05-22 00:00:00,69.000000,6.000000,11.510046,8.748117,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,2.000000,5.250000,3.000000,22.000000,78.000000,4.000000,29.000000,60.000000,4.000000,32.000000,45.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,7.000000,0.000000,6.000000,0.000000,4.000000,-9.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-9.900000e+01,0.000000,1.000000,0.000000,-99.000000,-99.000000,0.000000,0.000000e+00,0.000000e+00,-9.900000e+01,0.000000,2.000000,-99.000000,-9.000000,-9.000000,0.000000,-9.000000
50%,2.012010e+11,2012.000000,6.000000,15.000000,0.000000,2013-04-29 00:00:00,98.000000,8.000000,31.300213,43.746215,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,7.000000,4.000000,35.000000,101.000000,14.000000,67.000000,97.000000,14.000000,67.000000,98.500000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,8.000000,0.000000,8.000000,0.000000,7.000000,-9.000000,6.000000,11.000000,6.000000,8.000000,7.000000,11.000000,6.000000,9.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-9.900000e+01,0.000000,2.000000,0.000000,-99.000000,-99.000000,0.000000,1.000000e+04,0.000000e+00,0.000000e+00,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.015123e+11,2015.000000,9.000000,23.000000,0.000000,2016-05-10 00:00:00,160.000000,10.000000,34.557022,68.835918,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,7.000000,7.000000,14.000000,74.000000,175.000000,14.000000,68.000000,182.000000,14.000000,73.000000,182.000000,0.000000,1.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,8.000000,1.000000,10.000000,1.000000,9.000000,0.000000,6.000000,16.000000,8.000000,18.000000,9.000000,21.000000,6.000000,16.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,4.000000,-9.900000e+01,0.000000,4.000000,0.000000,0.000000,3.000000,0.000000,3.420000e+05,0.000000e+00,6.640600e+02,0.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,2.020123e+11,2020.000000,12.000000,31.000000,1.000000,2021-05-29 00:00:00,1004.000000,12.000000,74.633553,179.366667,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,9.000000,9.000000,7.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,1.000000,1.000000,1.000000,1.000000,25000.000000,406.000000,1.000000,10.000000,1.000000,10.000000,1.000000,10.000000,1.000000,13.000000,31.000000,13.000000,31.000000,13.000000,28.000000,12.000000,28.000000,1700.000000,1361.000000,500.000000,10878.000000,751.000000,200.000000,1.000000,7.000000,2.700000e+09,1.000000,17000.000000,86.000000,999.000000,2676.000000,1.000000,1.000000e+09,1.320000e+08,2.750000e+08,48000.000000,7.000000,2958.000000,1.000000,1.000000,1.000000,1.000000
std,1.351933e+09,13.519321,3.387098,8.801104,0.221066,NaN,111.714562,2.905697,18.137061,56.113029,0.984958,0.281308,0.107693,0.081636,0.340389,2.305025,0.733146,0.353007,0.320672,0.184962,2.029153,2.358046,2.089622,6.602032,30.599430,91.732261,5.732859,25.761594,122.995161,5.649132,25.870299,152.871895,0.264916,0.437663,0.389069,0.062561,194.556994,12.115647,0.997974,2.343068,0.872997,2.683832,0.473405,2.853488,4.318717,2.296739,6.485577,2.377310,7.727262,2.239521,8.731212,1.507212,8.192672,11.340882,5.109512,4.262644,40.916175,2.760472,1.560821,3.288812,0.481360,1.398607e+07,0.562180,183.207589,6.355005,77.612689,127.146650,1.255812,2.826923e+07,5.005760e+06,9.195574e+06,2567.718184,2.030311,64.494306,4.543800,4.640302,0.536943,4.677966

In [ ]:
# Set the 'max_columns' option to None to print all columns
pd.set_option('display.max_columns', None)

# Now, when you print the DataFrame,  display all columns without truncation
print(df)

             eventid  iyear  imonth  iday           approxdate  extended  \
0       197000000001   1970       7     2                  NaN         0
1       197000000002   1970       0     0                  NaN         0
2       197001000001   1970       1     0                  NaN         0
3       197001000002   1970       1     0                  NaN         0
4       197001000003   1970       1     0                  NaN         0
...              ...    ...     ...   ...                  ...       ...
209701  202012310015   2020      12    31  2020-12-31 00:00:00         0
209702  202012310016   2020      12    31  2020-12-31 00:00:00         0
209703  202012310017   2020      12    31                  NaN         0
209704  202012310018   2020      12    31                  NaN         0
209705  202012310019   2020      12    31                  NaN         1

       resolution  country         country_txt  region  \
0             NaT       58  Dominican Republic       2
1             NaT      130              Mexico       1
2             NaT      160         Philippines       5
3             NaT       78              Greece       8
4             NaT      101               Japan       4
...           ...      ...                 ...     ...
209701        NaT      228               Yemen      10
209702        NaT      228               Yemen      10
209703        NaT       75             Germany       8
209704        NaT        4         Afghanistan       6
209705        NaT       33        Burkina Faso      11

                         region_txt     provstate           city   latitude  \
0       Central America & Caribbean      National  Santo Domingo  18.456792
1                     North America       Federal    Mexico city  19.371887
2                    Southeast Asia        Tarlac        Unknown  15.478598
3                    Western Europe        Attica         Athens  37.997490
4                         East Asia       Fukouka        Fukouka  33.580412
...                             ...           ...            ...        ...
209701   Middle East & North Africa   Al Hudaydah          Sabaa  15.305307
209702   Middle East & North Africa   Al Hudaydah   Beit Maghari  13.931337
209703               Western Europe  Lower Saxony        Leipzig  51.342239
209704                   South Asia         Kabul          Kabul  34.523842
209705           Sub-Saharan Africa         Sahel          Kelbo  13.864252

         longitude  specificity  vicinity  \
0       -69.951164          1.0         0
1       -99.086624          1.0         0
2       120.599741          4.0         0
3        23.762728          1.0         0
4       130.396361          1.0         0
...            ...          ...       ...
209701   43.019490          2.0         0
209702   43.478924          2.0         0
209703   12.374772          1.0         0
209704   69.140304          1.0         0
209705   -1.161453          1.0         0

                                                 location  \
0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
209701                                                NaN
209702        The incident occurred in the Hays district.
209703                                                NaN
209704  The incident occurred in Khair Khana neighborh...
209705                                                NaN

                                                  summary  crit1  crit2  \
0                                                     NaN      1      1
1                                                     NaN      1      1
2                                                     NaN      1      1
3                                                     NaN      1      1
4                                                     NaN      1      1
...                                                   ...    ...    ...
209701  12/31/2020: Assailants fired mortar shells tar...      1      1
209702  12/31/2020: Assailants attempted to plant expl...      1      1
209703  12/31/2020: Assailants set fire to German Army...      1      1
209704  12/31/2020: Assailants shot and killed a civil...      1      1
209705  12/31/2020: Assailants attacked a Volunteers o...      1      1

        crit3  doubtterr  alternative             alternative_txt  multiple  \
0           1          0          NaN                         NaN       0.0
1           1          0          NaN                         NaN       0.0
2           1          0          NaN                         NaN       0.0
3           1          0          NaN                         NaN       0.0
4           1         -9          NaN                         NaN       0.0
...       ...        ...          ...                         ...       ...
209701      1          0          NaN                         NaN       0.0
209702      1          0          NaN                         NaN       0.0
209703      0          1          1.0  Insurgency/Guerilla Action       0.0
209704      1          0          NaN                         NaN       0.0
209705      0          1          1.0  Insurgency/Guerilla Action       0.0

        success  suicide  attacktype1                 attacktype1_txt  \
0             1        0            1                   Assassination
1             1        0            6     Hostage Taking (Kidnapping)
2             1        0            1                   Assassination
3             1        0            3               Bombing/Explosion
4             1        0            7  Facility/Infrastructure Attack
...         ...      ...          ...                             ...
209701        1        0            3               Bombing/Explosion
209702        1        0            3               Bombing/Explosion
209703        1        0            7  Facility/Infrastructure Attack
209704        1        0            2                   Armed Assault
209705        1        0            2                   Armed Assault

        attacktype2 attacktype2_txt  attacktype3 attacktype3_txt  targtype1  \
0               NaN             NaN          NaN             NaN         14
1               NaN             NaN          NaN             NaN          7
2               NaN             NaN          NaN             NaN         10
3               NaN             NaN          NaN             NaN          7
4               NaN             NaN          NaN             NaN          7
...             ...             ...          ...             ...        ...
209701          NaN             NaN          NaN             NaN         14
209702          NaN             NaN          NaN             NaN         14
209703          NaN             NaN          NaN             NaN          4
209704          NaN             NaN          NaN             NaN         14
209705          NaN             NaN          NaN             NaN          4

                      targtype1_txt  targsubtype1  \
0       Private Citizens & Property          68.0
1           Government (Diplomatic)          45.0
2               Journalists & Media          54.0
3           Government (Diplomatic)          46.0
4           Government (Diplomatic)          46.0
...                             ...           ...
209701  Private Citizens & Property          76.0
209702  Private Citizens & Property          76.0
209703                     Military          35.0
209704  Private Citizens & Property          83.0
209705                     Military          39.0

                                         targsubtype1_txt  \
0                                          Named Civilian
1       Diplomatic Personnel (outside of embassy, cons...
2                         Radio Journalist/Staff/Facility
3                                       Embassy/Consulate
4                                       Embassy/Consulate
...                                                   ...
209701                          House/Apartment/Residence
209702                          House/Apartment/Residence
209703  Military Transportation/Vehicle (excluding con...
209704                                          Protester
209705                                       Paramilitary

                                                    corp1  \
0                                                     NaN
1                             Belgian Ambassador Daughter
2                                        Voice of America
3                                                     NaN
4                                                     NaN
...                                                   ...
209701                                     Not Applicable
209702                                     Not Applicable
209703                                        German Army
209704                                     Not Applicable
209705  Volunteers of the Defence of the Fatherland (VDP)

                        target1  natlty1         natlty1_txt  targtype2  \
0                  Julio Guzman     58.0  Dominican Republic        NaN
1       Nadine Chaval, daughter     21.0             Belgium        NaN
2                      Employee    217.0       United States        NaN
3                  U.S. Embassy    217.0       United States        NaN
4                U.S. Consulate    217.0       United States        NaN
...                         ...      ...                 ...        ...
209701               Residences    228.0               Yemen        NaN
209702               Residences    228.0               Yemen        NaN
209703      Wolf-Class Vehicles     75.0             Germany        NaN
209704     Activist: Abdi Jahid      4.0         Afghanistan        NaN
209705    Paramilitary Position     33.0        Burkina Faso        NaN

       targtype2_txt  targsubtype2 targsubtype2_txt corp2 target2  natlty2  \
0                NaN           NaN              NaN   NaN     NaN      NaN
1                NaN           NaN              NaN   NaN     NaN      NaN
2                NaN           NaN              NaN   NaN     NaN      NaN
3                NaN           NaN              NaN   NaN     NaN      NaN
4                NaN           NaN              NaN   NaN     NaN      NaN
...              ...           ...              ...   ...     ...      ...
209701           NaN           NaN              NaN   NaN     NaN      NaN
209702           NaN           NaN              NaN   NaN     NaN      NaN
209703           NaN           NaN              NaN   NaN     NaN      NaN
209704           NaN           NaN              NaN   NaN     NaN      NaN
209705           NaN           NaN              NaN   NaN     NaN      NaN

       natlty2_txt  targtype3 targtype3_txt  targsubtype3 targsubtype3_txt  \
0              NaN        NaN           NaN           NaN              NaN
1              NaN        NaN           NaN           NaN              NaN
2              NaN        NaN           NaN           NaN              NaN
3              NaN        NaN           NaN           NaN              NaN
4              NaN        NaN           NaN           NaN              NaN
...            ...        ...           ...           ...              ...
209701         NaN        NaN           NaN           NaN              NaN
209702         NaN        NaN           NaN           NaN              NaN
209703         NaN        NaN           NaN           NaN              NaN
209704         NaN        NaN           NaN           NaN              NaN
209705         NaN        NaN           NaN           NaN              NaN

       corp3 target3  natlty3 natlty3_txt                               gname  \
0        NaN     NaN      NaN         NaN                              MANO-D
1        NaN     NaN      NaN         NaN  23rd of September Communist League
2        NaN     NaN      NaN         NaN                             Unknown
3        NaN     NaN      NaN         NaN                             Unknown
4        NaN     NaN      NaN         NaN                             Unknown
...      ...     ...      ...         ...                                 ...
209701   NaN     NaN      NaN         NaN     Houthi extremists (Ansar Allah)
209702   NaN     NaN      NaN         NaN     Houthi extremists (Ansar Allah)
209703   NaN     NaN      NaN         NaN                Left-wing extremists
209704   NaN     NaN      NaN         NaN                             Unknown
209705   NaN     NaN      NaN         NaN                             Unknown

       gsubname gname2 gsubname2 gname3 gsubname3 motive  guncertain1  \
0           NaN    NaN       NaN    NaN       NaN    NaN          0.0
1           NaN    NaN       NaN    NaN       NaN    NaN          0.0
2           NaN    NaN       NaN    NaN       NaN    NaN          0.0
3           NaN    NaN       NaN    NaN       NaN    NaN          0.0
4           NaN    NaN       NaN    NaN       NaN    NaN          0.0
...         ...    ...       ...    ...       ...    ...          ...
209701      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209702      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209703      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209704      NaN    NaN       NaN    NaN       NaN    NaN          0.0
209705      NaN    NaN       NaN    NaN       NaN    NaN          0.0

        guncertain2  guncertain3  individual  nperps  nperpcap  claimed  \
0               NaN          NaN           0     NaN       NaN      NaN
1               NaN          NaN           0     7.0       NaN      NaN
2               NaN          NaN           0     NaN       NaN      NaN
3               NaN          NaN           0     NaN       NaN      NaN
4               NaN          NaN           0     NaN       NaN      NaN
...             ...          ...         ...     ...       ...      ...
209701          NaN          NaN           0   -99.0       0.0      0.0
209702          NaN          NaN           0   -99.0       0.0      0.0
209703          NaN          NaN           0   -99.0       0.0      1.0
209704          NaN          NaN           0   -99.0       0.0      0.0
209705          NaN          NaN           0   -99.0       0.0      0.0

        claimmode                  claimmode_txt  claim2  claimmode2  \
0             NaN                            NaN     NaN         NaN
1             NaN                            NaN     NaN         NaN
2             NaN                            NaN     NaN         NaN
3             NaN                            NaN     NaN         NaN
4             NaN                            NaN     NaN         NaN
...           ...                            ...     ...         ...
209701        NaN                            NaN     NaN         NaN
209702        NaN                            NaN     NaN         NaN
209703        7.0  Posted to website, blog, etc.     NaN         NaN
209704        NaN                            NaN     NaN         NaN
209705        NaN                            NaN     NaN         NaN

       claimmode2_txt  claim3  claimmode3 claimmode3_txt  compclaim  \
0                 NaN     NaN         NaN            NaN        NaN
1                 NaN     NaN         NaN            NaN        NaN
2                 NaN     NaN         NaN            NaN        NaN
3                 NaN     NaN         NaN            NaN        NaN
4                 NaN     NaN         NaN            NaN        NaN
...               ...     ...         ...            ...        ...
209701            NaN     NaN         NaN            NaN        NaN
209702            NaN     NaN         NaN            NaN        NaN
209703            NaN     NaN         NaN            NaN        NaN
209704            NaN     NaN         NaN            NaN        NaN
209705            NaN     NaN         NaN            NaN        NaN

        weaptype1 weaptype1_txt  weapsubtype1  \
0              13       Unknown           NaN
1              13       Unknown           NaN
2              13       Unknown           NaN
3               6    Explosives          16.0
4               8    Incendiary           NaN
...           ...           ...           ...
209701          6    Explosives          11.0
209702          6    Explosives           8.0
209703          8    Incendiary          18.0
209704          5      Firearms           5.0
209705          5      Firearms           5.0

                                 weapsubtype1_txt  weaptype2 weaptype2_txt  \
0                                             NaN        NaN           NaN
1                                             NaN        NaN           NaN
2                                             NaN        NaN           NaN
3                          Unknown Explosive Type        NaN           NaN
4                                             NaN        NaN           NaN
...                                           ...        ...           ...
209701  Projectile (rockets, mortars, RPGs, etc.)        NaN           NaN
209702                                   Landmine        6.0    Explosives
209703                                 Arson/Fire        NaN           NaN
209704                           Unknown Gun Type        NaN           NaN
209705                           Unknown Gun Type        NaN           NaN

        weapsubtype2        weapsubtype2_txt  weaptype3 weaptype3_txt  \
0                NaN                     NaN        NaN           NaN
1                NaN                     NaN        NaN           NaN
2                NaN                     NaN        NaN           NaN
3                NaN                     NaN        NaN           NaN
4                NaN                     NaN        NaN           NaN
...              ...                     ...        ...           ...
209701           NaN                     NaN        NaN           NaN
209702          16.0  Unknown Explosive Type        NaN           NaN
209703           NaN                     NaN        NaN           NaN
209704           NaN                     NaN        NaN           NaN
209705           NaN                     NaN        NaN           NaN

        weapsubtype3 weapsubtype3_txt  weaptype4 weaptype4_txt  weapsubtype4  \
0                NaN              NaN        NaN           NaN           NaN
1                NaN              NaN        NaN           NaN           NaN
2                NaN              NaN        NaN           NaN           NaN
3                NaN              NaN        NaN           NaN           NaN
4                NaN              NaN        NaN           NaN           NaN
...              ...              ...        ...           ...           ...
209701           NaN              NaN        NaN           NaN           NaN
209702           NaN              NaN        NaN           NaN           NaN
209703           NaN              NaN        NaN           NaN           NaN
209704           NaN              NaN        NaN           NaN           NaN
209705           NaN              NaN        NaN           NaN           NaN

       weapsubtype4_txt                        weapdetail  nkill  nkillus  \
0                   NaN                               NaN    1.0      NaN
1                   NaN                               NaN    0.0      NaN
2                   NaN                               NaN    1.0      NaN
3                   NaN                         Explosive    NaN      NaN
4                   NaN                        Incendiary    NaN      NaN
...                 ...                               ...    ...      ...